[[bond]]
source = "tpknam1qqnkmfpzq4pxlwfevucssnap2lhxy5zkftrpypy4u239d30sjtlwser6wv9"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "100"

[bond.signatures]
tpknam1qqnkmfpzq4pxlwfevucssnap2lhxy5zkftrpypy4u239d30sjtlwser6wv9 = "signam1qrh3l6rwjxa8tjddpufy2343rjld4zdtal0wvpn6v49c4ecuzncyxsm6a5w8l6vp67y59rt6dl99fh75tk5d2ylsdrl9zxpcwaqm03qf05uua8"
